---
version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=crm
      - POSTGRES_USER=crm
    volumes:
      - ./initialization:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/crm -user=crmuser -password=crm -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
  crm-api:
    build: 
      context: ./api
    image: crm-api
    restart: unless-stopped
    environment:
       ConnectionStrings__PostgresConnection: "User ID=crmuser;Password=crm;Host=postgres;Port=5432;Database=crm;"
    depends_on:
        - flyway
    ports: 
      - 8081:80
  crm-frontend:
    build:
      context: ./Frontend/crm
      args:
        build_command: flutter build web --dart-define base_url=http://localhost:8081
    image: crm-frontend
    restart: unless-stopped
    ports:
      - 8083:80
    depends_on:
      - crm-api
volumes:
  postgres_data: